## Basics Of Python - Part 2 (Loops, Functions, Math Library, Strings)
#### Topics
1. While Loop
2. For Loop
3. Functions
4. Math Library
5. String Handling

##### Note: 
1. First Clean the Evironment (Go to "Kernel" Menu --> "Restart & Clean Output"
2. To execute the code --> Click on a cell and press cntrl + enter key

# 1: While Loop

### 1.1: While Loop (print 1 to 10)

In [1]:
#------------------------------------------------------------------------
# 1.1: While Loop (print 1 to 10)
#------------------------------------------------------------------------
i = 1
while i <= 10:
    print (i)
    i = i + 1

1
2
3
4
5
6
7
8
9
10

### 1.2: While Loop (print 10 to 1)

In [2]:
#------------------------------------------------------------------------
# 1.2: While Loop (print 10 to 1)
#------------------------------------------------------------------------
i = 10
while i > 0:
    print (i)
    i = i - 1

10
9
8
7
6
5
4
3
2
1

In [3]:
#------------------------------------------------------------------------
# 1.2: While Loop (print 10 to 1)
#------------------------------------------------------------------------
i = 10
while (i > 0):
    print (i)
    i -= 1
    x = 80    # With in the loop
y = 90        # Out of the loop

10
9
8
7
6
5
4
3
2
1

# 2: Range Function

### 2.1: Range Function

In [4]:
#------------------------------------------------------------------------
# 2.1: Range Function
#------------------------------------------------------------------------
range(10)  # No output; Only print function

range(0, 10)

In [5]:
#------------------------------------------------------------------------
# 2.2: Range Function
#------------------------------------------------------------------------
list(range(10)) # A list will print

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
#------------------------------------------------------------------------
# 2.3: Range Function
#------------------------------------------------------------------------
print ("range(10)        -->", list(range(10)))
print ("range(0,20)      -->", list(range(0,20)))
print ("range(10,20)     -->", list(range(10,20)))
print ("range(0,20,2)    -->", list(range(0,20,2)))
print ("range(-10,-20,2) -->", list(range(-10,-20,2)))
print ("range(-10,-20,-2)-->", list(range(-10,-20,-2)))

range(10)        --> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
range(0,20)      --> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
range(10,20)     --> [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
range(0,20,2)    --> [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
range(-10,-20,2) --> []
range(-10,-20,-2)--> [-10, -12, -14, -16, -18]

# 3: For Loop

### 3.1: For loop (print 1 to 10)

In [7]:
#------------------------------------------------------------------------
# 3.1: For loop (print 1 to 10)
#------------------------------------------------------------------------
for i in range(1,11):
    print (i)

1
2
3
4
5
6
7
8
9
10

### 3.2: For loop (print 1 to 20 with increment of 2)

In [8]:
#------------------------------------------------------------------------
# 3.2: For loop (print 1 to 20 with increment of 2)
#------------------------------------------------------------------------
for i in range(1,21,2):
    print (i)

1
3
5
7
9
11
13
15
17
19

### 3.3: For loop (print 0 to -10)

In [9]:
#------------------------------------------------------------------------
# 3.3: For loop (print 0 to -10)
#------------------------------------------------------------------------
for i in range(0,-10,1):
    print (i)

## No Output; Why ??

### 3.4: For loop (print 0 to -10)

In [10]:
#------------------------------------------------------------------------
# 3.4: For loop (print 0 to -10)
#------------------------------------------------------------------------
for i in range(0,-10,-1):
    print (i)

0
-1
-2
-3
-4
-5
-6
-7
-8
-9

### 3.5: Print table of 5

In [11]:
#------------------------------------------------------------------------
# 3.5: Print table of 5
#------------------------------------------------------------------------
for i in range(1,11):
    print (5,"*", i , "=", i * 5)

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

###### Assingment: WAP to print the table of n; where n will be given by the user

### 3.6: Sum all numbers from 1 to 10

In [12]:
#------------------------------------------------------------------------
# 3.6: Sum all numbers from 1 to 10
#------------------------------------------------------------------------
s = 0
for i in range(1,11):
    s = s + i
print ("Sum is --> ",s)

Sum is -->  55

### 3.7: Sum all numbers from 1 to 10

In [13]:
#------------------------------------------------------------------------
# 3.7: Sum all numbers from 1 to 10
#------------------------------------------------------------------------
print ("Sum is --> ", sum(range(1,11)))

Sum is -->  55

##### Assingment 3.1: WAP to print the table of 7, 9.
##### Assingment 3.2: WAP to print the table of n and n is given by user.
##### Assingment 3.3: WAP to add all the numbers from 1 to n and n is given by user.

# 4: Miscellaneous Example

### 4.1: Prime Number

In [15]:
#------------------------------------------------------------------------
# 4.1: Prime Number
#------------------------------------------------------------------------
n = int(input("Enter a No: "))
f = 0 
for i in range(2, n):
    if  n % i == 0: 
        f = 1
        break

if f == 0:
    print ("Prime")
else:
    print ("Not Prime")

Not Prime

### 4.2: Fibonacci Series

In [ ]:
#------------------------------------------------------------------------
# 4.2 Fibonacci Series
#------------------------------------------------------------------------
n = 10

a = 0
b = 1

print (a)
print (b)
for i in range(n):
    c = a + b
    print (c)
    a = b
    b = c

0
1
1
2
3
5
8
13
21
34
55
89

### 4.3: Factorial

In [ ]:
#------------------------------------------------------------------------
# 4.3: Factorial
#------------------------------------------------------------------------
n = 4

a = 1

for i in range(1, n + 1):
    a = a * i
print ("Factorial is :", a)

Factorial is : 24

# 5: Functions

### 5.1: Add two numbers

In [ ]:
#------------------------------------------------------------------------	
# 5.1: Add two numbers
#------------------------------------------------------------------------
def Add(a,b):
    c = a + b
    return c

print ("Add(10,20) -->", Add(10,20))
print ("Add(20,50) -->", Add(20,50)) 
print ("Add(80,200)-->", Add(80,200))

Add(10,20) --> 30
Add(20,50) --> 70
Add(80,200)--> 280

### 5.2: Prime number

In [ ]:
#------------------------------------------------------------------------	
# 5.2: Prime number
#------------------------------------------------------------------------
def IsPrime(n):
    for i in range(2, n):
        if n%i == 0:
            return 0
    return 1

print ("IsPrime(20) -->", IsPrime(20))
print ("IsPrime(23) -->", IsPrime(23))
print ("IsPrime(200)-->", IsPrime(200))
print ("IsPrime(37) -->", IsPrime(37))

IsPrime(20) --> 0
IsPrime(23) --> 1
IsPrime(200)--> 0
IsPrime(37) --> 1

### 5.3: Add 1 to n

In [ ]:
#------------------------------------------------------------------------
# 5.3: Add 1 to n
#------------------------------------------------------------------------
def AddN(n):
    s = sum(range(n + 1))
    return s

print ("AddN(10) -->", AddN(10))
print ("AddN(20) -->", AddN(20))
print ("AddN(50) -->", AddN(50))
print ("AddN(200)-->", AddN(200))

AddN(10) --> 55
AddN(20) --> 210
AddN(50) --> 1275
AddN(200)--> 20100

### 5.4: Default Parameter

In [ ]:
#------------------------------------------------------------------------
# 5.4: Default Parameter
#------------------------------------------------------------------------
def Add(a, b, d = 90):
    c = a + b + d
    return c

print ("Add(10,20)   -->", Add(10,20))
print ("Add(20,50,10)-->", Add(20,50,10))

Add(10,20)   --> 120
Add(20,50,10)--> 80

#### Assingment 5.1: WAP using function that add all odd numbers from 1 to n; n given by user.
#### Assingment 5.2: WAP using function that add all even numbers from 1 to n; n given by user.
#### Assingment 5.3: WAP using function that add all prime numbers from 1 to n; n given by user.

# 6: Math library

In [ ]:
#-----------------------------------------------------------------------
# 6: Math library
#-----------------------------------------------------------------------

import math as m
print ("exp(-200)    -->", m.exp(-200))  # Exponential function
print ("log(100,2)   -->", m.log(100,2)) # Log
print ("log(100,10)  -->", m.log(100,10))# Log
print ("log10(100)   -->", m.log10(100)) # Log 10
print ("m.cos(30)    -->", m.cos(90))    # cos
print ("m.sin(30)    -->", m.sin(30))    # sin
print ("m.tan(30)    -->", m.tan(30))    # tan
print ("m.sqrt(324)  -->", m.sqrt(324))
print ("m.ceil(89.9) -->", m.ceil(89.9))
print ("m.floor(89.9)-->", m.floor(89.9))

exp(-200)    --> 1.3838965267367376e-87
log(100,2)   --> 6.643856189774725
log(100,10)  --> 2.0
log10(100)   --> 2.0
m.cos(30)    --> -0.4480736161291701
m.sin(30)    --> -0.9880316240928618
m.tan(30)    --> -6.405331196646276
m.sqrt(324)  --> 18.0
m.ceil(89.9) --> 90
m.floor(89.9)--> 89

# 7: String Handling

### 7.1: String Declaration

In [ ]:
#------------------------------------------------------------------------
# 7.1: String Declaration
#------------------------------------------------------------------------
var1 = 'Hello Python'
var2 = "Hello Python"
print ("var1 -->", var1)
print ("var2 -->",var2)

var1 --> Hello Python
var2 --> Hello Python

### 7.2: Difference between single quote and double quote

In [ ]:
#------------------------------------------------------------------------
# 7.2: Difference between single quote and double quote
#------------------------------------------------------------------------
var1 = 'Hello "Python"'
var2 = "Hello 'Python'"
print ("var1 -->", var1)
print ("var2 -->",var2)

var1 --> Hello "Python"
var2 --> Hello 'Python'

In [ ]:
# No Error
print("It's python") # No Error

It's python

In [ ]:
# Error
print('It's python') # Error

SyntaxError: invalid syntax (<ipython-input-30-12fd05c3da0a>, line 2)

In [ ]:
# No Error; Use of \
print('It\'s python') # No Error

It's python

In [ ]:
# No Error
print('It"s python') # No Error

It"s python

### 7.3: Indexing in string

In [ ]:
#------------------------------------------------------------------------
# 7.3: Indexing in string
#------------------------------------------------------------------------
#Example 1:
var1 = "123456789"
print("var1     -->", var1)
print("var1[1]  -->", var1[1])
print("var1[2]  -->", var1[2])
print("var1[-1] -->", var1[-1])
print("var1[-2] -->", var1[-2])

var1     --> 123456789
var1[1]  --> 2
var1[2]  --> 3
var1[-1] --> 9
var1[-2] --> 8

In [ ]:
#Example 2:
var1 = "123456789"
print("var1       -->", var1)
print("var1[1:3]  -->", var1[1:3])
print("var1[2:]   -->", var1[2:])  #upto end
print("var1[2:5]  -->", var1[2:5]) #exclude index 5 
print("var1[:2]   -->", var1[:2])  # starting not specified
print("var1[:-1]  -->", var1[:-1])
print("var1[-4:-1]-->", var1[-4:-1])

var1       --> 123456789
var1[1:3]  --> 23
var1[2:]   --> 3456789
var1[2:5]  --> 345
var1[:2]   --> 12
var1[:-1]  --> 12345678
var1[-4:-1]--> 678

In [ ]:
#Example 3:
var1 = "123456789"
print("var1      -->", var1)
print("var1[::1] -->", var1[::2])        # No change, start from beginning, increment by 1 nd go upto last
print("var1[::-1]-->", var1[::-1])       # Reverse
print("var1[::-2]-->", var1[::-2])
print("var1[::2] -->", var1[::2])

var1      --> 123456789
var1[::1] --> 13579
var1[::-1]--> 987654321
var1[::-2]--> 97531
var1[::2] --> 13579

### 7.4: String length, upper, lower

In [ ]:
#------------------------------------------------------------------------
# 7.4: String length, upper, lower
#------------------------------------------------------------------------
var1 = "Python Programming"

print ("var1           --> ", var1)
print ("\nlength of var1 --> ", len(var1))

print ("\nUpper of var1  --> ", var1.upper())     # No change in the var1 variable
print ("var1           --> ", var1)

print ("\nLower of var1  --> ", var1.lower())
print ("var1           --> ", var1)

var1           -->  Python Programming

length of var1 -->  18

Upper of var1  -->  PYTHON PROGRAMMING
var1           -->  Python Programming

Lower of var1  -->  python programming
var1           -->  Python Programming

### 7.5: To save string in upper/lower permanetly

In [ ]:
#------------------------------------------------------------------------
# 7.5: To save string in upper/lower permanetly
#------------------------------------------------------------------------
var1 = "Python Programming"
print ("var1 --> ", var1)

var1 = var1.upper()               # Assign back to var1 variable
print ("var1 --> ", var1)

var1 -->  Python Programming
var1 -->  PYTHON PROGRAMMING

### 7.6: String formatting

In [ ]:
#------------------------------------------------------------------------
# 7.6: String formatting
#------------------------------------------------------------------------
name  = "Baljeet"    #=input("Enter your name: ")"
age   = 20           #=int(input("Enter your age: "))
price = 89.5         #=float(input("Enter the book price: "))
s = "Your name is %s, age is %d and book price is %f" %(name.upper(),age,price)
print (s)

Your name is BALJEET, age is 20 and book price is 89.500000

### 7.7: String in Triple Quotes

In [ ]:
#------------------------------------------------------------------------
# 7.7: String in Triple Quotes
#------------------------------------------------------------------------
para_str = """This is a long string that is made up of
several lines and non-printable characters such as
TAB ( \t ) and they will show up that way when displayed.
NEWLINEs within the string, whether explicitly given like
this within the brackets [ \n ], or just a NEWLINE within
the variable assignment will also show up.
"""
print (para_str)

This is a long string that is made up of
several lines and non-printable characters such as
TAB ( 	 ) and they will show up that way when displayed.
NEWLINEs within the string, whether explicitly given like
this within the brackets [
 ], or just a NEWLINE within
the variable assignment will also show up.

### 7.8: String strip - Remove white Spaces (space, new line, tab) from either side

In [ ]:
#---------------------------------------------------------------------------------
# 7.8: String strip - Remove white Spaces (space, new line, tab) from either side
#---------------------------------------------------------------------------------
s1 = " Indian Army    "
s2 = " Indian     Army    "
s3 = "Indian,Army,is,best"

print ("s1       --> ", s1, "\t\t   Length --> ", len(s1))
print ("s1 strip --> ", s1.strip(), "\t\t   Length --> ", len(s1.strip()))

print ("\ns2       --> ", s2, "\t   Length --> ", len(s2))
print ("s2 strip --> ", s2.strip(), "\t\t   Length --> ", len(s2.strip()))

print ("\ns3       --> ", s3, "\t   Length --> ", len(s3))
print ("s3 strip --> ", s3.strip(), "\t   Length --> ", len(s3.strip()))

s1       -->   Indian Army     		   Length -->  16
s1 strip -->  Indian Army 		   Length -->  11

s2       -->   Indian     Army     	   Length -->  20
s2 strip -->  Indian     Army 		   Length -->  15

s3       -->  Indian,Army,is,best 	   Length -->  19
s3 strip -->  Indian,Army,is,best 	   Length -->  19

### 7.9: String split

In [ ]:
#------------------------------------------------------------------------
# 7.9: String split
#------------------------------------------------------------------------
s1 = " Indian Army    "
s2 = " Indian     Army    "
s3 = "Indian,Army,is,best"

print ("s1                --> ", s1)
print ("s1 split          --> ", s1.split())

print ("\ns2                --> ", s2)
print ("s2 split          --> ", s2.split())
print ("s2 split with ',' --> ", s2.split(","))

print ("\ns3                --> ", s3)
print ("s3 split          --> ", s3.split())
print ("s3 split with ' ' --> ", s3.split(' '))

s1                -->   Indian Army
s1 split          -->  ['Indian', 'Army']

s2                -->   Indian     Army
s2 split          -->  ['Indian', 'Army']
s2 split with ',' -->  [' Indian     Army    ']

s3                -->  Indian,Army,is,best
s3 split          -->  ['Indian,Army,is,best']
s3 split with ' ' -->  ['Indian,Army,is,best']

### 7.10: Count in string

In [ ]:
#------------------------------------------------------------------------
# 7.10: Count in string
#------------------------------------------------------------------------
s1 = " Indian Army    "
print ("s1           -->", s1)
print ("s1 count ' ' -->", s1.count(' '))
print ("s1 count 'a' -->", s1.count('a'))
print ("s1 count 'an'-->", s1.count('an'))

s1           -->  Indian Army
s1 count ' ' --> 6
s1 count 'a' --> 1
s1 count 'an'--> 1

### 7.11: Reverse a String

In [ ]:
#------------------------------------------------------------------------
# 7.11: Reverse a String
#------------------------------------------------------------------------
s1 = "Indian Army"
print ("s1               -->", s1)
print ("s1[::1]          -->", s1[::1])
print ("s1[::-1]         -->", s1[::-1])
print ("s1[::-2]         -->", s1[::-2])
print ("s1[::2]          -->", s1[::2])

s1 = s1[::-1]
print ("s1 after reverse -->", s1)

s1               --> Indian Army
s1[::1]          --> Indian Army
s1[::-1]         --> ymrA naidnI
s1[::-2]         --> yr adI
s1[::2]          --> Ida ry
s1 after reverse --> ymrA naidnI

### 7.12: Palindrome

In [ ]:
#------------------------------------------------------------------------
# 7.12: Palindrome
#------------------------------------------------------------------------
s1 = "Indian Army"
s2 = "malayalam"
s3 = "madam"
s4 = "teacher"
print ("s1 -->", s1 == s1[::-1])
print ("s2 -->", s2 == s2[::-1])
print ("s3 -->", s3 == s3[::-1])
print ("s4 -->", s4 == s4[::-1])

s1 --> False
s2 --> True
s3 --> True
s4 --> False